---
video_input: 'udp://192.168.0.76:8090'
### USB Webcam on PC ###
#video_input: 0              # Input Must be OpenCV readable
### USB Webcam on TX2 ###
#video_input: 1
### Onboard camera on TX2 ### (need: apt-get install libxine2)
#video_input: "nvcamerasrc ! video/x-raw(memory:NVMM), width=(int)1280, height=(int)720,format=(string)I420, framerate=(fraction)30/1 ! nvvidconv flip-method=0 ! video/x-raw, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink"

force_gpu_compatible: False # If True with visualize False, speed up. Forces all CPU tensors to be allocated with Cuda pinned memory.
visualize: True             # Disable for performance increase
vis_text: True              # Display fps on visualization stream
max_frames: 5000            # only used if visualize==False
execution_seconds: 60       # only used if visualize==False
width: 160                  # OpenCV only supports 4:3 formats others will be converted
height: 120                 # 600x600 leads to 640x480
fps_interval: 5             # Interval [s] to print fps of the last interval in console
det_interval: 100           # intervall [frames] to print detections to console
det_th: 0.5                 # detection threshold for det_intervall
split_model: True           # Splits Model into a GPU and CPU session (currently only works for ssd_mobilenets)
log_device: False           # Logs GPU / CPU device placement
allow_memory_growth: True   # limits memory allocation to the actual needs
ssd_shape: 300              # used for the split model algorithm
                            # currently only supports ssd networks trained on 300x300 and 600x600 input
debug_mode: False           # Show FPS spike value

x_meter: 1.5                # IPM変換後の画像におけるxメートル(黒い部分も含む)
y_meter: 1                  # IPM変換後の画像におけるyメートル(黒い部分も含む)


# Change only if you use another model
model_name: 'ssd_mobilenet_v1_coco'

# mscoco
#model_path: 'models/ssd_mobilenet_v1_coco/frozen_inference_graph.pb'
#label_path: 'models/ssd_mobilenet_v1_coco/mscoco_label_map.pbtxt'
#num_classes: 90

# own data
model_path: 'models/ssd_mobilenet/roadsign.pb'
label_path: 'models/ssd_mobilenet/roadsign_label_map.pbtxt'
num_classes: 4
