---
host: '192.168.0.22'        # Server IP Address
port: 6666                  # Server TCP Port
image_input: 'images'       # input image dir
movie_input: 'input.mp4'    # mp4 or avi. Movie file.
#camera_input: 0            # USB Webcam on PC
camera_input: 1             # USB Webcam on TX2

force_gpu_compatible: False # If True with visualize False, speed up. Forces all CPU tensors to be allocated with Cuda pinned memory.
save_to_file: False         # movie or camera: ./output_movie/output_unixtime.avi. Save it in avi format to prevent compression degradation. Requires a lot of disk space.
                            # image: ./output_image/PATH_TO_FILE. Save it in image file.
visualize: True             # True: Show result image. False: Without image show.
vis_worker: False           # True: Visualization run on process. (With visuzalize:True)
max_vis_fps: 0              # >=1: Limit of show fps. 0: No limit - means try to spend full machine power for visualization. (With visualize:True.)
vis_text: True              # Display fps on result image. (With visualize:True.)
max_frames: 5000            # >=1: Quit when frames done. 0: no exit. (With visualize:False)
width: 160                  # Camera width.
height: 120                 # Camera height.
fps_interval: 5             # FPS console out interval and FPS stream length.
det_interval: 100           # intervall [frames] to print detections to console
det_th: 0.5                 # detection threshold for det_intervall
split_model: True           # Splits Model into a GPU and CPU session
log_device: False           # Logs GPU / CPU device placement
allow_memory_growth: True   # limits memory allocation to the actual needs
debug_mode: False           # Show FPS spike value
split_shape: 1917           # 1917, 3000, 3309, 5118, 7326, 51150. ExpandDims_1's shape.
debug_mode: False           # Show FPS spike value

x_meter: 1.5                # IPM変換後の画像におけるxメートル(黒い部分も含む)
y_meter: 1                  # IPM変換後の画像におけるyメートル(黒い部分も含む)


########################################
# model_type: 'nms_v1'
# split_shape: 1917
# This is for my own data
########################################
# ssd_mobilenet_v1_2017_11_17 own data
model_type: 'nms_v1'
model_path: 'models/ssd_mobilenet/roadsign.pb'
label_path: 'models/ssd_mobilenet/roadsign_label_map.pbtxt'
num_classes: 4
