site_name: FaBo RobotCarAI Docs
theme:
    name: material
    language: 'ja'
extra:
    search:
        language: 'jp'
markdown_extensions:
  - fontawesome_markdown
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.keys
  - markdown_fenced_code_tabs
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"  
  - 'stylesheets/extra.css'
plugins:
  - macros
